package com.packcheng.router.util;

/**
 * @author packcheng <a href="mailto:packcheng_jo@outlook.com">Contact me.</a>
 * @version 1.0
 * @since 2022/4/5 14:16
 */
public class Consts {
    // Generate
    public static final String PROJECT = "ZbcRouter";
    public static final String METHOD_GET = "get";
    public static final String NAME_OF_MAPPING = "RouterMapping_";
    public static final String NAME_OF_FOLDER_MAPPING_DOC = "router_mapping";
    public static final String NAME_OF_JSON = ".json";
    public static final String NAME_OF_FILE_MAPPING = "router_mapping_";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY ZBCROUTER.";
    public static final String PACKAGE_OF_GENERATE_DOCS = "com.packcheng.router.docs";
    public static final String PACKAGE_OF_GENERATE_FILE = "com.packcheng.router.routes";

    // Java type
    private static final String LANG = "java.lang";
    public static final String BYTE = LANG + ".Byte";
    public static final String SHORT = LANG + ".Short";
    public static final String INTEGER = LANG + ".Integer";
    public static final String LONG = LANG + ".Long";
    public static final String FLOAT = LANG + ".Float";
    public static final String DOUBEL = LANG + ".Double";
    public static final String BOOLEAN = LANG + ".Boolean";
    public static final String CHAR = LANG + ".Character";
    public static final String STRING = LANG + ".String";
    public static final String SERIALIZABLE = "java.io.Serializable";

    static final String PREFIX_OF_LOGGER = PROJECT + "::Compiler ";

    public static final String KEY_ROOT_PROJECT_DIR = "root_project_dir";
    public static final String KEY_DOC_URL = "url";
    public static final String KEY_DOC_DESCRIPTION = "description";
    public static final String KEY_DOC_REAL_PATH = "realPath";

    public static final String NO_ROOT_PROJECT_DIR_TIPS = "These no root_project_dir, at 'build.gradle', like :\n" +
            "android {\n" +
            "    kapt {\n" +
            "       arguments {\n" +
            "           \"arg(\"root_project_dir\", rootProject.projectDir.absolutePath)\n" +
            "       }\n" +
            "    }\n" +
            "}\n";

}
