{
  "formatVersion": "1.1",
  "component": {
    "group": "com.packcheng.plugin",
    "module": "method-tracker-gradle-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "method-tracker-gradle-plugin-1.0.0.jar",
          "url": "method-tracker-gradle-plugin-1.0.0.jar",
          "size": 48466,
          "sha512": "eacba5cd316be80b31bfd23510113094fca6c45fbd805fd91b9cccf109bdb4691f1c542914d6f7f0dc6f6a8567adb2d75236516279e54745e954f1c11b6a3cbc",
          "sha256": "02af639cc93fc0c6992258e84127cff92004a4247524760e9d788cbe84bc5ad5",
          "sha1": "903f9154af6f1153cbb4cfa5c55bee0000d3c8da",
          "md5": "e94cb8125cb062d8f9939f456852ca5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "method-tracker-gradle-plugin-1.0.0.jar",
          "url": "method-tracker-gradle-plugin-1.0.0.jar",
          "size": 48466,
          "sha512": "eacba5cd316be80b31bfd23510113094fca6c45fbd805fd91b9cccf109bdb4691f1c542914d6f7f0dc6f6a8567adb2d75236516279e54745e954f1c11b6a3cbc",
          "sha256": "02af639cc93fc0c6992258e84127cff92004a4247524760e9d788cbe84bc5ad5",
          "sha1": "903f9154af6f1153cbb4cfa5c55bee0000d3c8da",
          "md5": "e94cb8125cb062d8f9939f456852ca5c"
        }
      ]
    }
  ]
}
