{
  "formatVersion": "1.1",
  "component": {
    "group": "com.packcheng.router",
    "module": "router-runtime",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "router-runtime-1.0.0.aar",
          "url": "router-runtime-1.0.0.aar",
          "size": 36664,
          "sha512": "1ea9aa5626ee2e231b4e6ee03860913eca03f3000719bbde53c2994e8abb9c70c9cdd8864fc8752e16a77d26b5a5e0db9be3198a26c31ac0b3d3a1841155524e",
          "sha256": "e429b4ada4d6b118a2f225674f2eb9dcf22770ebb7ace0e32ed48353eb184a1d",
          "sha1": "8f997884cfd171d8ac944e062e7b8b79480a97c5",
          "md5": "28bfa702da29aab0693b515f969c7821"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "router-runtime-1.0.0.aar",
          "url": "router-runtime-1.0.0.aar",
          "size": 36664,
          "sha512": "1ea9aa5626ee2e231b4e6ee03860913eca03f3000719bbde53c2994e8abb9c70c9cdd8864fc8752e16a77d26b5a5e0db9be3198a26c31ac0b3d3a1841155524e",
          "sha256": "e429b4ada4d6b118a2f225674f2eb9dcf22770ebb7ace0e32ed48353eb184a1d",
          "sha1": "8f997884cfd171d8ac944e062e7b8b79480a97c5",
          "md5": "28bfa702da29aab0693b515f969c7821"
        }
      ]
    }
  ]
}
